# Generated by Django 5.0.9 on 2024-11-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=255)),
                ('costPerPaper', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'Paper',
            },
        ),
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.CharField(default='', max_length=255)),
                ('transaction_amount', models.IntegerField(default=0)),
                ('date_payment', models.DateTimeField(default='2024-01-01 12:00:00')),
            ],
            options={
                'db_table': 'Payment_history',
            },
        ),
        migrations.CreateModel(
            name='Print_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=255)),
                ('file_size', models.IntegerField(default=0)),
                ('owner_id', models.CharField(default='', max_length=255)),
                ('numberOfPages', models.IntegerField(default=0)),
                ('page_id', models.CharField(default='', max_length=255)),
                ('printerId', models.CharField(default='', max_length=255)),
                ('datetime', models.DateTimeField(default='2024-01-01 12:00:00')),
            ],
            options={
                'db_table': 'Print_history',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_type', models.CharField(default='', max_length=255)),
                ('enable_printing', models.BooleanField(default=True)),
                ('location', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'Printer',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(default='', max_length=50)),
                ('full_name', models.CharField(default='', max_length=255)),
                ('availablePages', models.IntegerField(default=0)),
                ('major', models.CharField(default='', max_length=255)),
                ('enrollment_year', models.DateField(default='2024-01-01')),
                ('buying_enabled', models.BooleanField(default=False)),
                ('working_location', models.CharField(default='', max_length=255)),
                ('department_name', models.CharField(default='', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
