# Generated by Django 5.0.9 on 2024-11-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_avaiablepages_user_availablepages_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userid',
            new_name='id',
        ),
    ]
