# Generated by Django 5.0.9 on 2024-11-25 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_requestlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestLog',
        ),
    ]
