# Generated by Django 5.0.9 on 2024-11-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_requestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='PrinterId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
