# Generated by Django 5.0.9 on 2024-11-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_printerid_print_history_printerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='page',
            field=models.IntegerField(default=1),
        ),
    ]
