# Generated by Django 5.0.9 on 2024-11-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_paper_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='print_history',
            name='datetime',
            field=models.DateTimeField(default='2024-01-01 12:00:00'),
        ),
    ]
