# Generated by Django 5.0.9 on 2024-12-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_print_history_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPaperBuying', models.IntegerField(default=0)),
                ('totalPaperPrinting', models.IntegerField(default=0)),
                ('datetime', models.DateField(default='2024-01-01')),
            ],
        ),
    ]
