# Generated by Django 5.0.9 on 2024-12-01 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_report'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='report',
            table='Report',
        ),
    ]
